create table IF NOT EXISTS user (
  id int primary key auto_increment,
  name varchar(50),
  password varchar(225)
) AUTO_INCREMENT = 1;

INSERT INTO user (id, name,password) VALUES (NULL,'marco','12345')
,(NULL,'admin','admin');

create table IF NOT EXISTS usercategory (
  id int primary key auto_increment,
  iduser int,
  description varchar(225)
) AUTO_INCREMENT = 1;

INSERT INTO usercategory (id, iduser, description) VALUES (NULL,0,'produto')
,(NULL,1,'product')
,(NULL,1,'relatory')
,(NULL,2,'product');


create table IF NOT EXISTS product (
  id int primary key auto_increment,
  name varchar(50),
  description varchar(225)
) AUTO_INCREMENT = 1;

INSERT INTO product (id, name,description) VALUES (NULL,'Raja','egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio.')
,(NULL,'Alisa','ac mi eleifend egestas. Sed pharetra, felis')
,(NULL,'Drake','lectus convallis est, vitae sodales')
,(NULL,'Isaac','massa rutrum magna. Cras')
,(NULL,'Odessa','feugiat metus sit')
,(NULL,'Rae','leo elementum sem,')
,(NULL,'Jasper','a, scelerisque sed, sapien. Nunc pulvinar arcu')
,(NULL,'Fay','mauris')
,(NULL,'Nigel','ultrices, mauris')
,(NULL,'Colleen','Nunc commodo')
,(NULL,'Dieter','elit. Curabitur')
,(NULL,'Irma','ullamcorper.')
,(NULL,'Ciaran','neque. Sed eget lacus. Mauris')
,(NULL,'Clinton','at fringilla purus mauris')
,(NULL,'Jena','et, eros. Proin ultrices.')
,(NULL,'Darryl','risus odio,')
,(NULL,'Keaton','erat. Vivamus nisi.')
,(NULL,'Alexandra','laoreet lectus quis massa. Mauris vestibulum, neque sed dictum')
,(NULL,'Lynn','enim nec tempus scelerisque, lorem ipsum sodales')
,(NULL,'Laith','vulputate eu, odio.')
,(NULL,'Shafira','nec')
,(NULL,'Perry','Integer id magna et')
,(NULL,'Germane','arcu. Nunc mauris. Morbi non sapien molestie orci')
,(NULL,'Victor','a feugiat tellus lorem eu metus. In')
,(NULL,'Willa','aliquam arcu. Aliquam ultrices iaculis')
,(NULL,'Tana','eu odio tristique pharetra.')
,(NULL,'Casey','euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate')
,(NULL,'Willa','commodo')
,(NULL,'Cally','Nulla semper')
,(NULL,'Chantale','Quisque fringilla euismod enim. Etiam gravida molestie arcu.')
,(NULL,'Travis','mi enim, condimentum')
,(NULL,'Sean','Nullam')
,(NULL,'Aquila','odio. Aliquam vulputate ullamcorper magna.')
,(NULL,'Ulysses','in, tempus eu, ligula.')
,(NULL,'Chancellor','Donec non justo. Proin')
,(NULL,'Hyacinth','blandit congue. In')
,(NULL,'Kelly','tempus, lorem fringilla')
,(NULL,'Patricia','enim non nisi. Aenean eget')
,(NULL,'Karina','Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non,')
,(NULL,'Quail','Cras vehicula')
,(NULL,'Eve','vel, faucibus id, libero.')
,(NULL,'Ori','tortor.')
,(NULL,'Channing','non, vestibulum nec, euismod in, dolor.')
,(NULL,'Hilda','Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent')
,(NULL,'Zenia','eu augue porttitor interdum. Sed auctor odio')
,(NULL,'Kalia','faucibus id, libero. Donec consectetuer mauris id sapien. Cras')
,(NULL,'Wade','blandit enim consequat purus. Maecenas libero est,')
,(NULL,'Jack','ut cursus luctus, ipsum leo elementum sem,')
,(NULL,'Kirestin','est,')
,(NULL,'MacKensie','orci. Ut semper pretium neque. Morbi quis urna. Nunc quis')
,(NULL,'Angelica','nonummy ut,')
,(NULL,'Keane','auctor. Mauris vel')
,(NULL,'Nathan','mauris, rhoncus id, mollis nec, cursus')
,(NULL,'Cathleen','Quisque varius. Nam porttitor scelerisque neque. Nullam nisl.')
,(NULL,'Roary','cursus, diam at pretium aliquet, metus urna convallis')
,(NULL,'Finn','sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit')
,(NULL,'Camden','nisl. Nulla eu neque')
,(NULL,'Mechelle','nascetur ridiculus mus.')
,(NULL,'Rhona','vel, venenatis vel, faucibus id, libero.')
,(NULL,'Amal','quam dignissim pharetra. Nam ac nulla. In')
,(NULL,'Ivy','vel quam dignissim pharetra. Nam ac')
,(NULL,'Preston','erat. Sed nunc est, mollis')
,(NULL,'Kerry','arcu. Vivamus sit amet')
,(NULL,'Alma','montes, nascetur ridiculus mus. Proin vel')
,(NULL,'Ifeoma','mauris elit, dictum eu, eleifend nec,')
,(NULL,'Sacha','risus a ultricies adipiscing, enim mi tempor lorem,')
,(NULL,'Harlan','Class aptent taciti sociosqu ad litora torquent per')
,(NULL,'Cecilia','ipsum ac')
,(NULL,'Nasim','diam luctus')
,(NULL,'Cheyenne','Duis mi enim, condimentum')
,(NULL,'Jelani','iaculis quis, pede. Praesent eu dui. Cum')
,(NULL,'Chloe','porta elit, a feugiat tellus')
,(NULL,'Adara','nibh vulputate mauris')
,(NULL,'Martina','in faucibus orci luctus et ultrices posuere cubilia Curae; Donec')
,(NULL,'Ori','commodo hendrerit. Donec')
,(NULL,'Orson','blandit')
,(NULL,'Blossom','Nam tempor diam dictum sapien. Aenean massa. Integer')
,(NULL,'Hadassah','Integer')
,(NULL,'Barclay','orci luctus et ultrices posuere cubilia Curae; Donec')
,(NULL,'Clarke','sapien,')
,(NULL,'Alana','eget, ipsum. Donec sollicitudin adipiscing ligula.')
,(NULL,'Kelly','nec')
,(NULL,'Amos','commodo at, libero. Morbi accumsan laoreet ipsum.')
,(NULL,'Peter','vitae, posuere at, velit. Cras lorem lorem, luctus')
,(NULL,'Faith','pede, malesuada vel, venenatis vel, faucibus')
,(NULL,'Julian','Cras vehicula aliquet libero. Integer in magna.')
,(NULL,'Jolie','aliquet. Proin velit. Sed malesuada')
,(NULL,'Ashton','vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu.')
,(NULL,'Shana','Aliquam auctor, velit eget laoreet posuere, enim')
,(NULL,'Ivy','lacus. Aliquam rutrum lorem ac risus. Morbi metus.')
,(NULL,'Colby','sollicitudin a, malesuada id, erat. Etiam vestibulum')
,(NULL,'Mari','arcu. Vivamus')
,(NULL,'Henry','magna')
,(NULL,'Kaseem','Pellentesque ut ipsum ac mi eleifend egestas. Sed')
,(NULL,'Steven','ornare placerat, orci lacus vestibulum lorem, sit amet ultricies')
,(NULL,'Kiona','fames')
,(NULL,'Alexandra','Phasellus ornare. Fusce mollis. Duis')
,(NULL,'Lavinia','pede')
,(NULL,'Naida','sapien. Cras dolor dolor,')
,(NULL,'Blossom','eleifend,');
